language: node_js
node_js:
- '0.11'
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJQNKNIS56HLWPF6A
  secret_access_key:
    secure: xWhKDPbfnPAs8bYBMVndeJ2x4hyZwc1xRWWYEvNaFot576xBdNTxbnmM3rTbF4k4Dn/9G8sfdxLsdok5nLYI6HYX1GMJu1Vc2hqj3z0CmLzteSuDO88tJGkKMUrLq4yCb7V2DtkdAtUyu3gqLneZGCCrCqaTH9QeprxQRsMmpqsEBbXVakjtCkxE7j9GwOgNkZ0DTjcLr+JE+RrD4RAIeX346Eum946EkmQbXj8y9NDBQkgYAqttZLQl+yoMxEuz4ltoiu6E89+rHs9LPJSZepCHdDZrPktm3fhtb52p6ahhFfWVrPBgdAN6GkLGWw0Rgmi9ppHsNo4tMp59gp0ZqU8HOHVt+SPA4gUFAsOJvWSnkGJYUb0xMsGJKccKXnfslXjAQycmsJGK+5HnIgZ/qBkC7UjyYFmFz1/4b58WyKUGmRFY4zji9q6Q/dksy+i6+/rPNyil7wspVBNOSv+LemEIbDvEuvigXezwxPiMmVJFvp2Vqr+DOF6+9/UQuTbCXAegPYsHZMT5XwpHoG/RZa8d8oXB5Wjwbukr0BH/nhNelOv+mPSTwfycNwafsL9eDTQ/yYMyyFi0dRctNGBsSA0vf7u1VUUob7PeNJPtdCk7vJE55GYiNJawl2Jk2pX1qwDZYMsjRTCTvZ2rMYtckGX3Zrtc0MPZ6w7fRKKnaW4=
  bucket: deploy-weeia
  upload-dir: pawelplewinski
  acl: ''
  on:
    repo: pawelplewinski/ciTestplewinski
